### ISSUE TITLE
Default module? Prepend input text with same module every time?

### ISSUE THREAD

**Issue by fyngyrz** [lrstanley/Code#119]
Hi. I have Code up and running, and have written a module for it, which is working fine.

For my application, it's the only module I *want* running. And it would be lovely if I didn't have to type the name of the module, since I already typed the intro character to activate the bot (which is$ in my setup.)

So right now, I have a module named `aa`

Invocation to get `aa` to process the line is:

$aa lineToBeProcessed

What I would like to do is be able to do this:

$lineToBeProcessed

Any tips, config setups, etc. that would either do this, or tell me what file I need to modify to get this done? I found `dispatch.py` but the workings are not immediately clear to me. If that's the right place and that's what has to be done, happy to try, but rather than dig through this until I understand everything, I'm hoping for more of a "go here, do that" type of hint. :)

If I knew where the input text was dispatched to the target module, I could probably just prepend all $-initiated input text with `aa ` and it would work as desired.

Thanks!

**Comment by lrstanley** [comment]
I believe I understand what you're looking to accomplish.

Rather than using something like this (note `cmds=['args']`):
https://github.com/lrstanley/Code/blob/cd3b668f96016b4a1eb0f2c3fefdb1c3b2e62848/modules/countdown.py#L5

Use a regex rule pattern, in your module hook. Some of the builtin modules support this (factoids, url, etc):
https://github.com/lrstanley/Code/blob/cd3b668f96016b4a1eb0f2c3fefdb1c3b2e62848/modules/factoids.py#L6

With the above example, it will essentially execute the `factoid()` function anytime there is a line matching:
```
`<text-here>
```

Just make sure to escape `$` (`\$`), since it is a regex-builtin. So maybe:

```python
@hook(rule='(?i)^\$(.*)$')
```

Let me know if this helps.

**Comment by lrstanley** [comment]
Also of note, you may want to use the whitelist config options to unload all other modules, and only load yours.

**Comment by fyngyrz** [comment]
Yes, I have just my module running.

I've set a rule as follows:

`@hook(rule=r'\$.*', event='PRIVMSG', priority='high')`

This is working. It catches any invocation of the bot with $.

I'd like to do one more thing; if it's me typing (that is, the nick is `fyngyrz` or owner of bot, whichever is easier) then I'd like to forego the $ prefix - that is, for me, I just want the bot to see everything I say. Possible?

**Comment by lrstanley** [comment]
In that case, I'd say just use the following, which will match all PRIVMSG events:

```python
@hook(rule=r'.*', event='PRIVMSG', priority='high')
```

Then -- inside of your module, manually:

   1. Check to see if it has `$` as the first character
   2. Otherwise, if it's from you, do whatever you want in that case
   3. Otherwise, ignore/skip the message.

**Comment by fyngyrz** [comment]
ok, working perfectly. Thank you so much for the help. Great bot. :)

**Comment by fyngyrz** [comment]
Okay, I got it. I found `code.msg()`, that's all I needed to get it going.

Again, great bot, thank you!
